from typing import Tuple


def hsl_to_rgb(h: int, s: int, l: int) -> Tuple[int, int, int]: ...
def hue_to_value(a: int, b: int, h: int) -> int: ...
def map(value: int, start1: int, stop1: int, start2: int, stop2: int) -> int: ...
