from typing import Tuple


def hsl_to_rgb(h: float, s: float, l: float) -> Tuple[int, int, int]: ...
def hue_to_value(a: float, b: float, h: float) -> float: ...
def map(value: float, start1: float, stop1: float, start2: float, stop2: float) -> float: ...
